### ISSUE TITLE
15!!!!!!!

### ISSUE THREAD

**Issue by hayato0718** [ryuchan00/computer_literacy#22]

**Comment by zd04inda** [comment]
http://inda-com.sakura.ne.jp/14/shimomen.html

**Comment by ryuchan00** [comment]
最後だぜ

**Comment by ryuchan00** [comment]
http://codecamp6475.lesson6.codecamp.jp//JS12/roulette.html

昔つくったルーレット

**Comment by ryuchan00** [comment]
先着1名でぱくっていいよ

```
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title>ルーレット</title>
<style type="text/css">
    #wrapper {
        width: 300px;
        height: 350px;
        border: solid 1px #000000;
        background-color: #000000;
        border-radius: 10px;
        background: -webkit-gradient(linear, left top, right bottom,
        from(#7cfc00), to(#008000))
    }
    #roulette-box {
        width: 270px;
        height: 270px;
        border: solid 5px #000000;
        background-color: #ffff00;
        border-radius: 10px;
        font-size: 35px;
        margin: 10px auto;
        padding: 5px;
        text-align: center;
    }
    #roulette td {
        width: 60px;
        height: 60px;
        /*css3限定、widthにborderを含めない！*/
        /*box-sizing: border-box;*/
        border: solid 1px #000000;
        margin: 0px;
    }
    #wrapper #button {
        margin: 10px auto;
        text-align: center;
    }
    .roulette {
        background-color: #da70d6;
    }
    .comp {
        background-color: #ffc0cb;
    }
</style> 
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script>
    //宣言部
    var idArray = ['#r1',
    '#r2',
    '#r3',
    '#r4',
    '#r5',
    '#r6',
    '#r7',
    '#r8',
    '#r9',
    '#r10',
    '#r11',
    '#r12',
    '#r13',
    '#r14',
    '#r15',
    '#r16'];
    
    var max = 16;
    var bingo = new Array();
    for(i = 1; i <= max; i++) {
        bingo.push(i);
    }
    var userStatus = 0;
    var roulette;
    var array = 0;
    
    //スタート
    function startFun() {
        if(userStatus === 1) {
            alert("すでにスタートしています");
        } else {
            userStatus = 1;
            if(max === bingo.length) {
                    //nothing    
                } else {
                    $(idArray[array]).addClass("comp")
                }
            if(0 === bingo.length) {
                alert("リセットボタンを押してください");
                userStatus = 0;
            } else {    
                roulette = setInterval(function(){
                    $(idArray[array]).removeClass("roulette");
                    random = Math.floor(Math.random() * bingo.length);
                    number = bingo[random];
                    array = number - 1;
                    $(idArray[array]).addClass("roulette")
                }, 100);
            }
        }
    }
    //ストップ
    function stopFun() {
        if(userStatus === 0) {
            alert("すでにストップしています");
        } else {
            userStatus = 0;
            if(0 === bingo.length) {
                alert("リセットボタンを押してください");
            } else {    
            clearInterval(roulette);
            bingo.splice(random, 1);
            }
        }
    }
    //リセット
    function resetFun() {
        if(userStatus === 1) {
            alert("ストップボタンを押してください");
        } else {
            userStatus = 0;
            clearInterval(roulette);
            bingo = new Array();
            for(i = 1; i <= max; i++) {
                bingo.push(i);
                array = i - 1;
                $(idArray[array]).removeClass("roulette");
                $(idArray[array]).removeClass("comp");
            }
        }
    }
    $(document).ready(
        function() {
        //alert('');
        //スタート
        $('#start').click(startFun);
        //ストップ
        $('#stop').click(stopFun);
        //リセット
        $('#reset').click(resetFun);
        }
    );
</script>
</head>
<body>
<div id=wrapper>
    <div id=roulette-box>
        <table id="roulette">
            <tr>
                <td id="r1">1</td>
                <td id="r2">2</td>
                <td id="r3">3</td>
                <td id="r4">4</td>
            </tr>
            <tr>
                <td id="r5">5</td>
                <td id="r6">6</td>
                <td id="r7">7</td>
                <td id="r8">8</td>
            </tr>
            <tr>
                <td id="r9">9</td>
                <td id="r10">10</td>
                <td id="r11">11</td>
                <td id="r12">12</td>
            </tr>
            <tr>
                <td id="r13">13</td>
                <td id="r14">14</td>
                <td id="r15">15</td>
                <td id="r16">16</td>
            </tr>
        </table>
    </div>
    <div id="button">
        <button id="start">スタート</button>
        <button id="stop">ストップ</button>
        <button id="reset">リセット</button>
    </div>
</div>
</body>
</html>
```

**Comment by ryuchan00** [comment]
http://kmaebashi.com/programmer/tetris/program.html

jsでテトリス

**Comment by zd04inda** [comment]
[Super-Mario-JS-master(1).zip](https://github.com/ryuchan00/computer_literacy/files/3437709/Super-Mario-JS-master.1.zip)

**Comment by hayato0718** [comment]
Toyo Tiresブランドで知られるToyo Tire＆Rubber Co Ltdは、タイヤによる騒音を低減する技術を開発したと述べています。
具体的には、（1）悪路走行時の低騒音、（2）路面通過時の低騒音などのロードノイズを最大75％低減でき、低騒音化に貢献します。快適な車内スペース。 2019年初頭に発売予定のタイヤに適用される予定です。
自動車を運転するときにタイヤによって引き起こされる２種類の騒音がある。一つはロードノイズです。路面の凹凸によりタイヤが揺れていると、その振動が車軸に伝わり、ロードノイズが発生します。
もう1つはパターンノイズです。タイヤと路面との間で発生した音が車体や窓を介して車内空間に伝わると、パターンノイズとなる。
今回、東洋ゴムは前者（ロードノイズ）の低減を目指しました。パターンノイズのレベルはタイヤ接地面の形状によって決定されますが、ロードノイズは部分的にタイヤ内部の空気の振動によって引き起こされます。騒音の原因は、空洞共振と呼ばれる現象で、ドラムのように空気が内部で共振します。
ロードノイズを減らすことは難しかったので、ロードノイズを減らすことは大きな改善につながると東洋ゴムは考えました。
Toyo Tire＆Rubberは、タイヤ内の空気の流れに注目しました。流体シミュレーションを何度も実行することによって、同社は回転するタイヤ内を移動する空気の可視化に成功し、2つの流れがあることを発見しました。 １つは周方向（回転方向）であり、もう１つは垂直方向（タイヤの中心に向かう方向）である。
気流の知識があれば、共鳴によって発生する音の流れを知ることが可能になります。
穴に通すことで騒音を低減
空洞共振、ひいてはロードノイズを低減するために、東洋ゴムはポリウレタン製の装置を開発し、それをタイヤの内周に沿って取り付けた。この装置は多孔質フィルムと１６個の円筒形スポンジからなる。各スポンジは１０〜１２ｇ（質量）の重さであり、そしてポリウレタンは一般的に使用される工業用ポリウレタンよりも高い耐久性を有する。
共鳴音が多孔質フィルムおよびスポンジと接触する面積を増大させる目的で、スポンジは多孔質フィルムを垂直方向に引っ張ってアーチの形状を形成する。
音が穴を通過すると、その音量は減少します。共鳴音が多孔質フィルムまたは円筒形スポンジを通過すると、音の一部が摩擦熱に変わります。摩擦熱にならない残りの音は、まるでそれが渦巻いているかのように穴の近くに留まります。その結果、音が広がらず、音量が小さくなります。
「当社の技術は気流を利用するという点で他社の技術とは異なります」とToyo Tire＆Rubberは述べた。
他の会社は吸音材をタイヤの内周に取り付ける。
Toyo Tire＆Rubberは新技術を使用してタイヤを試作し、それをミニバンに適用して車両をテストしました。その結果、この装置を装備していない従来のタイヤと比較して、200〜250Hzの低周波数帯域でノイズが最大約12dB減少しました。同社の計算によると、これは75％のノイズ低減に相当します。
Toyo Tire＆Rubberの執行役員である森屋学は、自動車メーカー、特にヨーロッパを拠点とする高級車メーカーは、高品質で快適な車内スペースの実現が期待されているため、そのような技術に対する強い需要があります。
量産車に吸音材などを付着させる他のタイヤメーカーの技術をすでに海外の製造業者が採用しています。例えば、Audi AGとTesla Incはこれらの技術を使用することが増えている、と彼は言った。一方、日本の自動車メーカーは積極的に使っていないようです。
この分野で新たに登場したToyo Tire＆Rubberは、電気自動車（EV）市場の新技術をターゲットにしています。エンジンの代わりにモーターを使用するEVは、通常のガソリン車よりもはるかに静かです。しかしながら、タイヤによって引き起こされるノイズがよりはっきりと聞こえることができるので、低いノイズレベルは問題となり得る。
EVの使用は、自動運転技術と並行して広がると予想されます。誰も車輪をとらなくてもよい車内スペースは居間のようになるでしょう。次世代自動車の分野での存在感を高めるために、同社は「静かなタイヤ」の技術開発を強化することを計画している。



すみません、翻訳を逃がしています。。。

**Comment by hayato0718** [comment]
tech 
Toyo Tire & Rubber cuts road noise by 75%
Sep. 4, 2018 05:20 am JST 14 Comments 
By Kaoru Kubono 
TOKYO 
Toyo Tire & Rubber Co Ltd, which is known for the Toyo Tires brand, says it has developed a technology to reduce noise caused by tires.
Specifically, it can reduce road noises such as (1) low noise generated at the time of traveling on a rough road surface and (2) road noise generated at the time of going over road seams by up to 75%, contributing to realizing a comfortable in-vehicle space. It is expected to be applied to tires to be released in early 2019.
There are two kinds of noise caused by tires at the time of driving a vehicle. One is road noise. When tires are being shaken due to irregularities on the road surface, the vibration is transmitted to the axles, causing road noise.
The other is pattern noise. When sound generated between tires and the road surface is transmitted to the in-vehicle space via the body and windows, it becomes pattern noise.
This time, Toyo Tire & Rubber aimed to reduce the former (road noise). While the level of pattern noise is determined by the shape of the tire grounding surface, road noise is caused partly by the vibration of air inside tires. What causes the noise is a phenomenon called "cavity resonance," in which air resonates inside like a drum.
It was difficult to reduce road noise, so Toyo Tire & Rubber considered that the reduction of road noise would result in a great improvement.
Toyo Tire & Rubber focused on the airflow inside a tire. By carrying out fluid simulations many times, the company succeeded in visualizing air moving inside a rotating tire and found that there are two flows. One is in the circumferential direction (the direction of the rotation), and the other is in the vertical direction (the direction toward the center of the tire).
With the knowledge of airflow, it becomes possible to know the flow of sound generated by the resonance.
Noise reduced by passing it through hole
To reduce cavity resonance and, thus, road noise, Toyo Tire & Rubber developed a device made of polyurethane and attached it along the inner circumference of a tire. The device consists of a porous film and 16 cylindrical sponges. Each sponge weighs 10-12g (mass), and the polyurethane has a higher durability than commonly-used industrial polyurethanes.
The sponges pull the porous film in the vertical direction to form the shape of an arch in the aim of increasing the area in which the resonance sound contacts the porous film and sponges.
When sound passes through a hole, its volume diminishes. When resonance sound passes through the porous film or cylindrical sponge, part of the sound turns into frictional heat. The rest of the sound, which does not turn into frictional heat, stays near the hole as if it is swirling. As a result, the sound does not spread, and its volume decreases.
"Our technology is different from other companies' technologies in that it utilizes airflow," Toyo Tire & Rubber said.
Other companies attach a sound-absorbing material to the inner circumference of a tire.
Toyo Tire & Rubber prototyped a tire by using the new technology, applied it to a minivan and tested the vehicle. As a result, compared with conventional tires that are not equipped with the device, noise was reduced by up to about 12dB in a low-frequency band of 200-250Hz. This is equivalent to a noise reduction of 75%, according to a calculation made by the company.
There is a strong demand for such technologies from automakers, especially Europe-based luxury car manufacturers, because they are expected to realize a high-quality, comfortable in-vehicle space, said Manabu Moriya, executive officer of Toyo Tire & Rubber.
Several overseas manufactures have already employed other tire manufacturers' technologies that attach a sound-absorbing material, etc, for mass-produced vehicles. For example, Audi AG and Tesla Inc are increasingly using those technologies, he said. On the other hand, Japanese automakers do not seem to be actively using them.
Toyo Tire & Rubber, which is a new comer in the field, targets the new technology at the market for electric vehicles (EVs). EVs, which use a motor in place of an engine, are much quieter than normal gasoline vehicles. However, the low noise level can be a problem because noises caused by tires can be heard more clearly.
The use of EVs is expected to spread in tandem with autonomous driving technologies. In-vehicle spaces where no one has to take the wheel will become like living rooms. To enhance its presence in the field of next-generation vehicles, the company plans to strengthen the technological development of the "quiet tire."
© Nikkei Technology Online

**Comment by hayato0718** [comment]
2nd Writing Argument

Toyo Tires are revolutionized in terms of road noise

Noise includes road noise and pattern noise. Knowing the air flow had a good effect on the tires.

We developed technology to reduce the noise caused by tires. Works well on rough roads and on any road surface. There are two types of noise when driving a car. Road noise and tire pattern noise. Toyo focused on road noise. Focus on the air flow inside the tire and know that there are two air flows. Among them, it was found that it was linked to noise by resonance. Cavity resonance can be used by processing a newly developed porous film. As a result, frictional heat decreased and noise decreased.”Our technology is different from other companies’technologies in that it untilizes airflow,” There is a demand for minivans and luxury cars, but it is desirable to use them for electric cars. This is because the interior of the car will be able to be more comfortable.

My opinion was that competing with the development of road noise reduction technology could make a better tire.

**Comment by hayato0718** [comment]
2nd Writing Argument

Toyo Tires are revolutionized in terms of road noise

First, noise includes road noise and pattern noise. Knowing the air flow had a good effect on the tires.

To begin with, we developed technology to reduce the noise caused by tires. For example, works well on rough roads and on any road surface. There are two types of noise when driving a car. Road noise and tire pattern noise. Next, “Toyo’ focused on road noise. Then focus on the air flow inside the tire and know that there are two air flows. Among them, it was found that it was linked to noise by resonance. What is more, cavity resonance can be used by processing a newly developed porous film. In addition to that, frictional heat decreased and noise decreased. Finally,”Our technology is different from other companies’technologies in that it untilizes airflow,” There is a demand for minivans and luxury cars, but it is desirable to use them for electric cars. This will mean because the interior of the car will be able to be more comfortable.

In conclusion, was that competing with the development of road noise reduction technology could make a better tire. All things considered, in my opinion Toyo Tires make from great

**Comment by w1920033** [comment]
演習2までのを送ります。

[演習.txt](https://github.com/ryuchan00/computer_literacy/files/3441743/default.txt)

**Comment by w1920033** [comment]
レポートも送っておきます。

[レポート.txt](https://github.com/ryuchan00/computer_literacy/files/3441744/default.txt)

**Comment by ryuchan00** [comment]
渡邊さんのレポート、読んでいて惚れ惚れする 💯

**Comment by hayato0718** [comment]
わたなべ先生最高です！！！！！
参考にさせていただきます。

**Comment by hayato0718** [comment]
```コンピュータリテラシレポート ＃15
学籍番号:1920003
氏名:伊東 隼人
提出日付:2019/07/31

[課題の再掲]

JavaScriptを使い簡単に視差効果(パララックス)効果を持つwebページをつくる。


[実施したこととその結果]


ソースコードを貼り付けます。


<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>（円、や楕円）</title>
    <style>
      body {
            width: 70%;
            margin: 200px auto 200px auto;
      }
      
      div {
            position: relative;
      }
      
      
      .ball1 {
            width: 90%;
            padding-top: 50%;
            background-color: #f00;
            opacity: 0.5;
            border-radius: 50%;
      }
      
      .ball2 {
            width: 90%;
            padding-top: 70%;
            background-color: #0f0;
            opacity: 0.5;
            border-radius: 50%;
            top: -150px;
            left: 40%;
      }
      
      .ball3 {
            width: 60%;
            padding-top: 90%;
            border-radius: 50%;
            top: -200px;
            background-color: #00f;
            opacity: 0.5;
      }
      
      .ball4 {
            width: 55%;
            padding-top: 60%;
            border-radius: 70%;
            top: -100px;
            left: 40%;
            background-color: #a0f;
            opacity: 0.5;
      }
    </style>
  </head>
  <body>

    
    <div class="rellax ball1" data-rellax-speed="-7"></div>
    <div class="rellax ball2" data-rellax-speed="0"></div>
    <div class="rellax ball3" data-rellax-speed="5"></div>
    <div class="rellax ball4" data-rellax-speed="10"></div>




[考察]

HTMLの属性に「data-rellax-speed」を記述を付与することで画面をスクロールした際、指定した速度で「もの」が動かせるので印象付けさせるのに良い効果をあたえられた。物体に速度差をつけることで印象操作させたい情報をより強く残すことができると推察できる。
実際、普通のwebページよりも客観的に見ていて印象に残りやすいと思いました。

さらに、様々な効果をhtmlページに付与させることができそうです。


[アンケート]
Q1. JavaScriptのような高水準言語と前にやった機械語(アセンブリ言語)を比較してどのように感じますか。

JavaScriptも便利に作用すると感じましたがアセンブリ言語から逃げてはいけないと思いました。ソースコードを自在に書き起こせるくらいになれなければ、職業とするのは難しいのかもしれません。


Q2. テストケースを書くなどのソフトウェア開発の考え方についてどのように思いましたか。

いわゆるアナログな考え方だと思いましたが、すべてのソフトウェア開発も元をたどれば初歩の初歩としてこういったテストをされているのかもしれません。大事な考え方だと思いました。

Q3. ここまでの科目全体を通して、学べたこと、学びたかったけど学べなかったことは何ですか。その他感想や、この科目の今後改善した方がよいこと、今後も維持した方がよいことの指摘もどうぞ。

Latex文書作成頃から、自分でも意欲的になり課題にとりくんで参りましたが、それ以前の課題は比較的簡単なものを選んでしまい、あまり身になっていない自覚があります。長期休暇中にもう一度すべての課題に目を通しておきたいと思いました。

また、後期のプログラミング講義のおいてけぼりをしないよう、予習や友人の力を借りて勉強しようと思います。

**Comment by hayato0718** [comment]
https://paiza.hatenablog.com

この辺のをすごくパクりました。

**Comment by ryuchan00** [comment]
https://github.com/ryuchan00/computer_literacy/blob/master/15/assignment15.txt

書き途中っす

**Comment by zd04inda** [comment]
心が荒んでいるのか、渡辺さんのレポが文字化けする！

**Comment by ryuchan00** [comment]
更新しました！完成版です！
https://github.com/ryuchan00/computer_literacy/blob/master/15/assignment15.txt

**Comment by ryuchan00** [comment]
@zd04inda 文字コードかな

**Comment by zd04inda** [comment]
ギリギリ課題提出完了！
http://inda-com.sakura.ne.jp/tetris/

**Comment by zd04inda** [comment]
<img width="1053" alt="スクリーンショット 2019-08-03 0 05 19" src="https://user-images.githubusercontent.com/34466928/62379694-7122e900-b582-11e9-879b-2d216e17cc74.png">

**Comment by hayato0718** [comment]
おめでとうございます！！！！
すばらしい！！！

**Comment by ryuchan00** [comment]
お疲れさまでした！！！！１
